# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obops < Formula
  desc "ObsidianOps Command Line Interface for creating Minecraft servers"
  homepage "https://github.com/NickAwrist/obsidian-ops-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/NickAwrist/obsidian-ops-cli/releases/download/v0.1.0/obsidian-ops-cli_Darwin_x86_64.tar.gz"
      sha256 "f2ff86c9262a1d8057f464b1f7f88ea6e3cd4aa9add8fa5b945fadd62df46e6e"

      def install
        bin.install "obops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/NickAwrist/obsidian-ops-cli/releases/download/v0.1.0/obsidian-ops-cli_Darwin_arm64.tar.gz"
      sha256 "9d1ba2a21f36651abf2aa6ccca1c5747dfddec6e7e1a0377e42cc706619e62d7"

      def install
        bin.install "obops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/NickAwrist/obsidian-ops-cli/releases/download/v0.1.0/obsidian-ops-cli_Linux_x86_64.tar.gz"
      sha256 "9842bb84566ff70af5ca1f8146cff9b7a17dc544660fb0d1cf219e38670e21ca"
      def install
        bin.install "obops"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/NickAwrist/obsidian-ops-cli/releases/download/v0.1.0/obsidian-ops-cli_Linux_arm64.tar.gz"
      sha256 "dd9325d35eccd5a4294c5b4b5f0622ccbe0b0f9f54cc25d551385f21e40e6dda"
      def install
        bin.install "obops"
      end
    end
  end

  test do
    system "#{bin}/obops --version"
  end
end
